import pyautogui
from time import sleep
import webbrowser

# while True:
#     print(pyautogui.position())
#     sleep(1)

sleep(1)
pyautogui.press('win')
sleep(1)
pyautogui.typewrite("wire")
sleep(1)
pyautogui.press("enter")
sleep(8)
pyautogui.doubleClick(527, 676) 
sleep(20)
pyautogui.click(50, 70)

    
sleep(1)
pyautogui.keyDown('ctrl')
pyautogui.press('s')
pyautogui.keyUp('ctrl')
sleep(3)
pyautogui.typewrite('wire')
sleep(1)
pyautogui.press("tab")
sleep(1)
pyautogui.press('down', 2)
sleep(1)
pyautogui.press('enter')
sleep(1)
pyautogui.press('tab')
sleep(1)
pyautogui.press('enter')
sleep(3)
pyautogui.keyDown('alt')
sleep(1)
pyautogui.press('tab')
sleep(1)
pyautogui.keyUp('alt')
sleep(1)
pyautogui.keyDown('ctrl')
pyautogui.press('tab')
pyautogui.keyUp('ctrl')
sleep(1)
pyautogui.click(1807, 65)
sleep(1)
webbrowser.open('https://www.google.com/maps/d/u/0/')
sleep(5)
pyautogui.click(303, 446)
sleep(5)
pyautogui.click(420, 400)
sleep(1)
pyautogui.click(318, 481)
sleep(1)
pyautogui.click(770, 614)
sleep(5)
pyautogui.press('click')
sleep(3)
pyautogui.click(140, 431)
sleep(2)
pyautogui.click(878, 718)
sleep(3)
pyautogui.typewrite("map.kml")
sleep(1)
pyautogui.press('enter')
